<?xml  version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="http://www.iata.org/IATA/2015/BIX/00/IATA_Baggage_ULD_RQ" elementFormDefault="qualified" version="2.000" xmlns:cns="http://www.iata.org/IATA/2015/BIX/00/IATA_Baggage_CommonTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.iata.org/IATA/2015/BIX/00/IATA_Baggage_ULD_RQ" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" id="IATA2026.2"><xs:import namespace="http://www.iata.org/IATA/2015/BIX/00/IATA_Baggage_CommonTypes" schemaLocation="IATA_Baggage_CommonTypes.xsd"/>
<xs:element name="IATA_Baggage_ULD_RQ">
<xs:annotation>
<xs:documentation>Instructions to handle baggage ULD from airline to handler</xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:sequence>
<xs:element name="Signature" type="cns:DigitalSignatureType" minOccurs="0" maxOccurs="1">
<xs:annotation>
<xs:documentation>Payload information for this notification message.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="ULD_Allocation" type="cns:InstructionForULD_AllocationType" minOccurs="1" maxOccurs="1">
<xs:annotation>
<xs:documentation>Active baggage ULD allocation (part of ULD journey) including relevant details</xs:documentation>
</xs:annotation>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
