<?xml version="1.0"?>
<xs:schema xmlns:cns="http://www.iata.org/IATA/2015/00/2021.1/IATA_OffersAndOrdersCommonTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.iata.org/IATA/2015/00/2021.1/IATA_OffersAndOrdersMessage" targetNamespace="http://www.iata.org/IATA/2015/00/2021.1/IATA_OffersAndOrdersMessage" elementFormDefault="qualified" version="3.000" id="IATA2021.1">
	<xs:import namespace="http://www.iata.org/IATA/2015/00/2021.1/IATA_OffersAndOrdersCommonTypes" schemaLocation="IATA_OffersAndOrdersCommonTypes.xsd"/>
	<xs:element name="IATA_ServiceDeliveryRS">
		<xs:annotation>
			<xs:documentation>The Airline responds with all relevant information about the Service to be delivered with the latest status (which the Airline may have changed as a result of receiving the request).</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="1" maxOccurs="1">
					<xs:element name="Error" type="cns:ErrorType" minOccurs="1" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>Contains information related to errors detected during processing of the preceding request.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Response" type="cns:ServiceDeliveryResponseType" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Service Delivery RS response information.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:choice>
				<xs:element name="AugmentationPoint" type="AugmentationPoint" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Party" type="cns:PartyType" minOccurs="1" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>Message/ Transaction Party(s) information. Note that information about parties is intended for business use, it is not intended for transaction authentication and routing of the message.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PayloadAttributes" type="cns:IATA_PayloadStandardAttributesType" minOccurs="0" maxOccurs="1">
					<xs:annotation>
						<xs:documentation>IATA standard payload attributes.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="BaggageAllowanceIDKey">
			<xs:selector xpath="./Response/DataLists/BaggageAllowanceList/BaggageAllowance"/>
			<xs:field xpath="BaggageAllowanceID"/>
		</xs:key>
		<xs:key name="PaxJourneyIDKey">
			<xs:selector xpath="./Response/DataLists/PaxJourneyList/PaxJourney"/>
			<xs:field xpath="PaxJourneyID"/>
		</xs:key>
		<xs:key name="PaxIDKey">
			<xs:selector xpath="./Response/DataLists/PaxList/Pax"/>
			<xs:field xpath="PaxID"/>
		</xs:key>
		<xs:key name="PaxSegmentIDKey">
			<xs:selector xpath="./Response/DataLists/PaxSegmentList/PaxSegment"/>
			<xs:field xpath="PaxSegmentID"/>
		</xs:key>
		<xs:key name="PenaltyIDKey">
			<xs:selector xpath="./Response/DataLists/PenaltyList/Penalty"/>
			<xs:field xpath="PenaltyID"/>
		</xs:key>
		<xs:key name="PriceClassIDKey">
			<xs:selector xpath="./Response/DataLists/PriceClassList/PriceClass"/>
			<xs:field xpath="PriceClassID"/>
		</xs:key>
		<xs:key name="SeatProfileIDKey">
			<xs:selector xpath="./Response/DataLists/SeatProfileList/SeatProfile"/>
			<xs:field xpath="SeatProfileID"/>
		</xs:key>
		<xs:key name="ServiceDefinitionIDKey">
			<xs:selector xpath="./Response/DataLists/ServiceDefinitionList/ServiceDefinition"/>
			<xs:field xpath="ServiceDefinitionID"/>
		</xs:key>
		<xs:keyref name="PaxSegmentIDKeyKeyRef1" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Response/DataLists/ContactInfoList/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PenaltyIDKeyKeyRef1" refer="PenaltyIDKey">
			<xs:selector xpath="./Response/DataLists/FareList/FareGroup/FareDetail/FareComponent/FareRule/PenaltyRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef2" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Response/DataLists/FareList/FareGroup/FareDetail/FareComponent/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PriceClassIDKeyKeyRef1" refer="PriceClassIDKey">
			<xs:selector xpath="./Response/DataLists/FareList/FareGroup/FareDetail/FareComponent/PriceClassRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxIDKeyKeyRef1" refer="PaxIDKey">
			<xs:selector xpath="./Response/DataLists/FareList/FareGroup/FareDetail/PaxRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxJourneyIDKeyKeyRef1" refer="PaxJourneyIDKey">
			<xs:selector xpath="./Response/DataLists/OriginDestList/OriginDest/PaxJourneyRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef3" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Response/DataLists/PaxJourneyList/PaxJourney/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef4" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Response/DataLists/PaxList/Pax/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxIDKeyKeyRef2" refer="PaxIDKey">
			<xs:selector xpath="./Response/DataLists/PaxList/Pax/PaxRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PenaltyIDKeyKeyRef2" refer="PenaltyIDKey">
			<xs:selector xpath="./Response/DataLists/PenaltyList/Penalty/FareDetail/FareComponent/FareRule/PenaltyRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef5" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Response/DataLists/PenaltyList/Penalty/FareDetail/FareComponent/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PriceClassIDKeyKeyRef2" refer="PriceClassIDKey">
			<xs:selector xpath="./Response/DataLists/PenaltyList/Penalty/FareDetail/FareComponent/PriceClassRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxIDKeyKeyRef3" refer="PaxIDKey">
			<xs:selector xpath="./Response/DataLists/PenaltyList/Penalty/FareDetail/PaxRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="BaggageAllowanceIDKeyKeyRef1" refer="BaggageAllowanceIDKey">
			<xs:selector xpath="./Response/DataLists/ServiceDefinitionList/ServiceDefinition/ServiceDefinitionAssociation/BaggageAllowanceRef/BaggageAllowanceRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="SeatProfileIDKeyKeyRef1" refer="SeatProfileIDKey">
			<xs:selector xpath="./Response/DataLists/ServiceDefinitionList/ServiceDefinition/ServiceDefinitionAssociation/SeatProfileRef/SeatProfileRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="ServiceDefinitionIDKeyKeyRef1" refer="ServiceDefinitionIDKey">
			<xs:selector xpath="./Response/DataLists/ServiceDefinitionList/ServiceDefinition/ServiceDefinitionAssociation/ServiceBundle/ServiceDefinitionRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxIDKeyKeyRef4" refer="PaxIDKey">
			<xs:selector xpath="./Response/Order/OrderItem/CancelRestrictions/PaxRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxIDKeyKeyRef5" refer="PaxIDKey">
			<xs:selector xpath="./Response/Order/OrderItem/ChangeRestrictions/PaxRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef6" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Response/Order/OrderItem/Service/BookingRef/BookingEntity/Org/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef7" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Response/Order/OrderItem/Service/DeliveredOrderServiceAssociation/PaxSegmentRef/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="SeatProfileIDKeyKeyRef2" refer="SeatProfileIDKey">
			<xs:selector xpath="./Response/Order/OrderItem/Service/DeliveredOrderServiceAssociation/SeatOnLeg/Seat/SeatProfileRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="ServiceDefinitionIDKeyKeyRef2" refer="ServiceDefinitionIDKey">
			<xs:selector xpath="./Response/Order/OrderItem/Service/DeliveredOrderServiceAssociation/ServiceDefinitionRef/ServiceDefinitionRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxIDKeyKeyRef6" refer="PaxIDKey">
			<xs:selector xpath="./Response/Order/OrderItem/Service/PaxRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef8" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Participant/Aggregator/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef9" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Participant/Corporation/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef10" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Participant/EnabledSystem/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef11" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Participant/RetailPartner/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef12" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Participant/TravelAgency/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef13" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Recipient/Aggregator/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef14" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Recipient/Corporation/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef15" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Recipient/EnabledSystem/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef16" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Recipient/RetailPartner/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef17" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Recipient/TravelAgency/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef18" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Sender/Aggregator/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef19" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Sender/Corporation/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef20" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Sender/EnabledSystem/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef21" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Sender/RetailPartner/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
		<xs:keyref name="PaxSegmentIDKeyKeyRef22" refer="PaxSegmentIDKey">
			<xs:selector xpath="./Party/Sender/TravelAgency/ContactInfo/PaxSegmentRefID"/>
			<xs:field xpath=" ."/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="AugmentationPoint">
		<xs:annotation>
			<xs:documentation>Implementer-Augmented Structure.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:any namespace="##other" processContents="lax" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
